<!DOCTYPE html>
<html>



<head>

       <title>      *****  RASCUNHO HTML  ******       </title>

</head>





<body>
 
    
** Botões 
    <button>Click me</button>
    
   
   
    <br>
    <br>
    <br>
    <br>
    
    <p> Site Google
        <a href="https://www.google.com">This is a link</a>
    </p>


    <br>
    <br>
    <br>
    <br>
    
    <ul>
        <li>Lista 1 com simbolo bolinha</li>
        <li>Lista 2</li>
        <li>Lista 3</li>
      </ul>
      
      <ol>
        <li>lista numerada</li>
        <li>lista numerada</li>
        <li>lista numerada</li>
        <li>lista numerada</li>
        
      </ol>


      <br>
      <br>
      <br>
      <br>
      
    <img src="lele.jpg"  width="80" height="100">

    <br>
    <br>
    <br>
    <br>

    
    
    <h1>Um titulo  H1 </h1>
    <h2>Um titulo  H2</h2>
    <h3>Um titulo H3 </h3>
    <h4>Um titulo H4 </h4>
    <h5>Um titulo H5</h5>

<br>
<br>
<br>
<br>


  
    <p>Forma de um Paragrafo</p>
    <p>Outro Paragrafo    </p>


    Pular a Linha pode ser com << BR >> <br> oK

    <br>
    <br>
    <br>
    <br>
    
  
  
  </body>




 
 
  <br>
  <br>
  <br>
  <br>
  



<footer>
Rodapé
</footer>



</html>
